# Core Colors
background            #16130b
foreground            #e9e2d4
selection_foreground  #e0c46d
selection_background  #3c2f00
cursor                #e0c46d
cursor_text_color     #16130b

# Regular Colors
color0  #16130b
color1  #ffb4ab
color2  #e0c46d
color3  #accfaf
color4  #fee086
color5  #f0e1bb
color6  #d4c6a1
color7  #e9e2d4

# Bright Colors
color8  #3d392f
color9  #ffb4ab
color10 #e0c46d
color11 #accfaf
color12 #fee086
color13 #f0e1bb 
color14 #d4c6a1
color15 #e9e2d4
