# Core Colors
background            #13140d
foreground            #e4e3d7
selection_foreground  #bcce81
selection_background  #293500
cursor                #bcce81
cursor_text_color     #13140d

# Regular Colors
color0  #13140d
color1  #ffb4ab
color2  #bcce81
color3  #a1d0c5
color4  #d8eb9a
color5  #e0e6c4
color6  #c4caa9
color7  #e4e3d7

# Bright Colors
color8  #393a31
color9  #ffb4ab
color10 #bcce81
color11 #a1d0c5
color12 #d8eb9a
color13 #e0e6c4 
color14 #c4caa9
color15 #e4e3d7
