# Core Colors
background            #12140d
foreground            #e3e3d7
selection_foreground  #b9cf84
selection_background  #263500
cursor                #b9cf84
cursor_text_color     #12140d

# Regular Colors
color0  #12140d
color1  #ffb4ab
color2  #b9cf84
color3  #a1d0c7
color4  #d4ec9d
color5  #dee6c5
color6  #c2caaa
color7  #e3e3d7

# Bright Colors
color8  #383a32
color9  #ffb4ab
color10 #b9cf84
color11 #a1d0c7
color12 #d4ec9d
color13 #dee6c5 
color14 #c2caaa
color15 #e3e3d7
