
$image = /home/jayfaza/wallpapers/255.jpg
$background = rgba(19120dff)

$image = /home/jayfaza/wallpapers/255.jpg
$error = rgba(ffb4abff)

$image = /home/jayfaza/wallpapers/255.jpg
$error_container = rgba(93000aff)

$image = /home/jayfaza/wallpapers/255.jpg
$inverse_on_surface = rgba(382f28ff)

$image = /home/jayfaza/wallpapers/255.jpg
$inverse_primary = rgba(895120ff)

$image = /home/jayfaza/wallpapers/255.jpg
$inverse_surface = rgba(f0dfd6ff)

$image = /home/jayfaza/wallpapers/255.jpg
$on_background = rgba(f0dfd6ff)

$image = /home/jayfaza/wallpapers/255.jpg
$on_error = rgba(690005ff)

$image = /home/jayfaza/wallpapers/255.jpg
$on_error_container = rgba(ffdad6ff)

$image = /home/jayfaza/wallpapers/255.jpg
$on_primary = rgba(4e2600ff)

$image = /home/jayfaza/wallpapers/255.jpg
$on_primary_container = rgba(ffdcc4ff)

$image = /home/jayfaza/wallpapers/255.jpg
$on_primary_fixed = rgba(2f1400ff)

$image = /home/jayfaza/wallpapers/255.jpg
$on_primary_fixed_variant = rgba(6d3a09ff)

$image = /home/jayfaza/wallpapers/255.jpg
$on_secondary = rgba(422b1aff)

$image = /home/jayfaza/wallpapers/255.jpg
$on_secondary_container = rgba(ffdcc4ff)

$image = /home/jayfaza/wallpapers/255.jpg
$on_secondary_fixed = rgba(2a1707ff)

$image = /home/jayfaza/wallpapers/255.jpg
$on_secondary_fixed_variant = rgba(5b412fff)

$image = /home/jayfaza/wallpapers/255.jpg
$on_surface = rgba(f0dfd6ff)

$image = /home/jayfaza/wallpapers/255.jpg
$on_surface_variant = rgba(d6c3b7ff)

$image = /home/jayfaza/wallpapers/255.jpg
$on_tertiary = rgba(2f330cff)

$image = /home/jayfaza/wallpapers/255.jpg
$on_tertiary_container = rgba(e3e7afff)

$image = /home/jayfaza/wallpapers/255.jpg
$on_tertiary_fixed = rgba(1a1d00ff)

$image = /home/jayfaza/wallpapers/255.jpg
$on_tertiary_fixed_variant = rgba(464a20ff)

$image = /home/jayfaza/wallpapers/255.jpg
$outline = rgba(9f8d82ff)

$image = /home/jayfaza/wallpapers/255.jpg
$outline_variant = rgba(51443bff)

$image = /home/jayfaza/wallpapers/255.jpg
$primary = rgba(ffb780ff)

$image = /home/jayfaza/wallpapers/255.jpg
$primary_container = rgba(6d3a09ff)

$image = /home/jayfaza/wallpapers/255.jpg
$primary_fixed = rgba(ffdcc4ff)

$image = /home/jayfaza/wallpapers/255.jpg
$primary_fixed_dim = rgba(ffb780ff)

$image = /home/jayfaza/wallpapers/255.jpg
$scrim = rgba(000000ff)

$image = /home/jayfaza/wallpapers/255.jpg
$secondary = rgba(e4bfa7ff)

$image = /home/jayfaza/wallpapers/255.jpg
$secondary_container = rgba(5b412fff)

$image = /home/jayfaza/wallpapers/255.jpg
$secondary_fixed = rgba(ffdcc4ff)

$image = /home/jayfaza/wallpapers/255.jpg
$secondary_fixed_dim = rgba(e4bfa7ff)

$image = /home/jayfaza/wallpapers/255.jpg
$shadow = rgba(000000ff)

$image = /home/jayfaza/wallpapers/255.jpg
$source_color = rgba(fea359ff)

$image = /home/jayfaza/wallpapers/255.jpg
$surface = rgba(19120dff)

$image = /home/jayfaza/wallpapers/255.jpg
$surface_bright = rgba(413731ff)

$image = /home/jayfaza/wallpapers/255.jpg
$surface_container = rgba(261e18ff)

$image = /home/jayfaza/wallpapers/255.jpg
$surface_container_high = rgba(312822ff)

$image = /home/jayfaza/wallpapers/255.jpg
$surface_container_highest = rgba(3c332dff)

$image = /home/jayfaza/wallpapers/255.jpg
$surface_container_low = rgba(221a14ff)

$image = /home/jayfaza/wallpapers/255.jpg
$surface_container_lowest = rgba(140d08ff)

$image = /home/jayfaza/wallpapers/255.jpg
$surface_dim = rgba(19120dff)

$image = /home/jayfaza/wallpapers/255.jpg
$surface_tint = rgba(ffb780ff)

$image = /home/jayfaza/wallpapers/255.jpg
$surface_variant = rgba(51443bff)

$image = /home/jayfaza/wallpapers/255.jpg
$tertiary = rgba(c6ca95ff)

$image = /home/jayfaza/wallpapers/255.jpg
$tertiary_container = rgba(464a20ff)

$image = /home/jayfaza/wallpapers/255.jpg
$tertiary_fixed = rgba(e3e7afff)

$image = /home/jayfaza/wallpapers/255.jpg
$tertiary_fixed_dim = rgba(c6ca95ff)

